### ISSUE TITLE
Should the bot create json files if not found?

### ISSUE THREAD

**Issue by egelmex** [ellxc/piperbot#53]
```
Traceback (most recent call last):
  File "piperbot.py", line 586, in <module>
    bot.load_plugin_from_module(plugin_)
  File "piperbot.py", line 145, in load_plugin_from_module
    self.load_plugin(Class)
  File "piperbot.py", line 168, in load_plugin
    func()
  File "/home/me92/documents/projects/piperbot/plugins/karma.py", line 14, in onload
    with open('karma.json', 'r') as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'karma.json'
```

**Comment by ellxc** [comment]
yeah it should, forgot to do this!
