### ISSUE TITLE
Bot does not close down cleanly when sent SIGTERM

### ISSUE THREAD

**Issue by egelmex** [ellxc/piperbot#57]
```
^CTraceback (most recent call last):
  File "piperbot.py", line 111, in run
    message = self.in_queue.get(timeout=10)
  File "/usr/lib64/python3.4/queue.py", line 176, in get
    self.not_empty.wait(remaining)
  File "/usr/lib64/python3.4/threading.py", line 294, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "piperbot.py", line 605, in <module>
    bot.run()
  File "piperbot.py", line 117, in run
    self.shutdown()
  File "piperbot.py", line 125, in shutdown
    server.disconnect(message="shutting down")
  File "/home/me92/documents/projects/piperbot/serverconnection.py", line 96, in disconnect
    self.socket.send(('QUIT :' + message + '\r\n').encode())
BrokenPipeError: [Errno 32] Broken pipe


```

**Comment by egelmex** [comment]
it takes two ctrl-C to kill it, with second one outputing

```
^CException ignored in: <module 'threading' from '/usr/lib64/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib64/python3.4/threading.py", line 1060, in join
    self._wait_for_tstate_lock()
  File "/usr/lib64/python3.4/threading.py", line 1076, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```
